import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import datetime


def generate_pdf(title: str, content: str) -> bytes:
    """Generate a styled PDF from title and content."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "SubTitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#666666"),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName="Helvetica",
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#222222"),
        spaceAfter=8,
        leading=18,
        fontName="Helvetica",
        alignment=TA_LEFT,
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#999999"),
        alignment=TA_CENTER,
        fontName="Helvetica-Oblique",
    )

    story = []

    # Title
    story.append(Paragraph(title.title(), title_style))

    # Date subtitle
    date_str = datetime.datetime.now().strftime("%B %d, %Y • %I:%M %p")
    story.append(Paragraph(f"generated by mr volt chatbot • {date_str}", subtitle_style))

    # Divider
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3a86ff")))
    story.append(Spacer(1, 0.5 * cm))

    # Content — split by newlines
    lines = content.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.3 * cm))
            continue
        safe_line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(safe_line, body_style))

    # Footer spacer
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("coded by @riyanshV • t.me/ProjectPythons", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
